[package]
name = "rnetmgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlink-packet-route = "0.8.0"
netlink-sys="0.7.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "3.0.0-beta.4"
