[package]
name = "rnetmgr"
version = "0.1.0"
authors = ["Seimizu Joukan <saimizi@gmail.com>"]
edition = "2018"
repository = "git@gitlab.com:joukan/netmgr.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netlink-packet-route = "0.8.0"
netlink-sys={version =  "0.7.0", features = ["tokio_socket"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "3.0.0-beta.4"
log4rs = "1.0.0"
log = "0.4.14"
tokio = {version = "1", features = ["full"]}
cfg-if = "1.0.0"
bytes = "1.1.0"

[features]
default = []
